services:
  roman:
    image: big_john
    build: .
    volumes:
      - ./hey.txt:/mnt/heytilRoman.txt
    tty: true
  server:
    image: nginx
    ports:
      - "8000:80"
    volumes:
      - ./hey.txt:/usr/share/nginx/html/index.html
